<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>             <!-- Enables nullable reference types -->
    <ImplicitUsings>enable</ImplicitUsings> <!-- Enables common using directives -->
    <AssemblyName>InsuranceSys.Domain</AssemblyName>
    <RootNamespace>InsuranceSys.Domain</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>