<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interface\ILeadRepository.cs" />
    <Compile Remove="LeadService.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InsuranceSys.Domain\InsuranceSys.Domain.csproj" />
  </ItemGroup>

</Project>
