<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e1d078a8-fcfc-4efc-8e61-949e04a0f5f7</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="App_Data\**" />
    <Compile Remove="wwwroot\assets\js\pages\crud\datatables\basic\**" />
    <Content Remove="App_Data\**" />
    <Content Remove="wwwroot\assets\js\pages\crud\datatables\basic\**" />
    <EmbeddedResource Remove="App_Data\**" />
    <EmbeddedResource Remove="wwwroot\assets\js\pages\crud\datatables\basic\**" />
    <None Remove="App_Data\**" />
    <None Remove="wwwroot\assets\js\pages\crud\datatables\basic\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Views\Customer\AddEditCustomerV1.cshtml" />
    <Content Remove="Views\Customer\AddEditCustomerV2.cshtml" />
    <Content Remove="Views\Customer\_CommonPolicyDetails_working.cshtml" />
    <Content Remove="Views\Customer\_MotorPolicyDetailsPartial_working.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BuildBundlerMinifier" Version="3.2.449" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="7.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.18.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InsuranceSys.Application\InsuranceSys.Application.csproj" />
    <ProjectReference Include="..\InsuranceSys.Domain\InsuranceSys.Domain.csproj" />
    <ProjectReference Include="..\InsuranceSys.Infrastructure\InsuranceSys.Infrastructure.csproj" />
  </ItemGroup>
</Project>
